Commodities:
    Electricity:
        InputDataPath: "ExampleSystems/SmallNewEngland/Electricity"
        HoursPerTimeStep: 1
    Hydrogen:
        InputDataPath: "ExampleSystems/SmallNewEngland/Hydrogen"
        HoursPerTimeStep: 1
    NaturalGas:
        InputDataPath: "ExampleSystems/SmallNewEngland/NaturalGas"
        HoursPerTimeStep: 1
PeriodLength: 24
HoursPerSubperiod: 24

