name: CI
on:
  push:
    branches:
      - main
      - develop 
    tags: ['*']
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        version:
          - "1.6" # LTS (64-bit Linux)
          - '1'   # latest stable 1.x Julia release (Linux)
        os:
          - ubuntu-latest
        arch:
          - x64
        include: # additional tests [Windows,Julia-nightly]
          - os: [windows-latest,macOS-latest]
            version: '1' # latest stable 1.x Julia release
            arch: x64
          - os: ubuntu-latest
            version: 'nightly'
            arch: x64
            allow_failure: true
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
